
wp_host: '34.231.242.199'
wp_username: 'imsudo'
wp_password: 'ZAZe oHgd qtGc O1bj hbx5 ghkJ'
wp_mediaurl: 'http://34.231.242.199/wp-json/wp/v2/media'
wp_posts: 'http://34.231.242.199/wp-json/wp/v2/posts'
